### ISSUE TITLE
[EPIC] Ibis Conference Talks & Tutorials (Q2)

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/talks#32]
We have multiple accepted talks/and tutorials to prepare, as well as proposals to write in this quarter. This is a meta issue to track the progress of this work. 

For a detailed status on each specific proposal and conference submission, go to https://github.com/orgs/ibis-project/projects/3/views/1

To deliver in Q2 (to be updated as we learn about previous submissions): 

- [x] LinkedIn's Stream Processing meetup - April 24, 2024 https://github.com/ibis-project/talks/issues/33
- [x] PyCon US May 15-18th 2024
       - May 15th - 3h Ibis tutorial: https://github.com/ibis-project/talks/issues/8
       - May 17th - Ibis Charla (talk about Ibis in Spanish): https://github.com/ibis-project/talks/issues/10
       - May 17th - Ibis testing talk in Maintainers Summit
       - Coordinate Open Space with DuckDB people

- [x] Berlin Buzzwords June 9-11th 2024 
       - Talk: Streaming doesn’t have to be hard https://github.com/ibis-project/talks/issues/24

- [x] Pydata London June 14-16th 2024
     - Tutorial (joint with Kedro): https://github.com/ibis-project/talks/issues/25

Conferences To submit proposal in Q2:

- [x] SC 2024 - Atlanta 11/17-22 - CFP closes 04/19
- ~~[ ] DuckCon 5 - Seattle 08/15 - CFP closes 04/29~~
- [x] OSDC West - SF 10/29-31 - CFP closes 05/20

**Comment by ncclementi** [comment]
## Weekly Update
04/17/2024

- Naty, Gil and Deepyaman are working on a tutorial proposal for SC 2024 jointly with Fernanda and Kae. The content is focused on Ibis and IbisML

**Comment by chloeh13q** [comment]
Hey Naty - could you add the LinkedIn meetup here too? It's on April 24. Thanks!

**Comment by ncclementi** [comment]
## Weekly Update
04/24/2024

- Ibis tutorial for SC 2024 submitted
- Phillip and Chloe delivered the talk LinkedIn's Stream Processing meetup https://github.com/ibis-project/talks/issues/33
- Scipy 2024 proposal notices:
    - Ibis Tutorial ACCEPTED - https://github.com/ibis-project/talks/issues/22
    - Ibis General Talk ACCEPTED - https://github.com/ibis-project/talks/issues/23
    - Ibis Geospatial Talk ACCEPTED - https://github.com/ibis-project/talks/issues/20
    - Ibis Testing Talk REJECTED - https://github.com/ibis-project/talks/issues/21

**Comment by ncclementi** [comment]
## Weekly Update
05/02/2024

- KDD tutorial proposal was rejected

**Comment by ncclementi** [comment]
## Weekly Update

(05/17 and 05/22)

### PyConUS 2024

- Ibis tutorial (recorded it will be up on youtube at some point)

Part of the Ibis team (Gil, Phillip, Naty and Jim) gave a successful 3h Tutorial at PyCon US 2024. We received great feedback about the delivery, easy installation process (using codespaces), and the content itself. We also asked for points of improvements to the participants. In this issue you can find the participants "what we can improve feedback" as well as our lessons learned https://github.com/ibis-project/ibis-tutorial/issues/30

- Phillip's Maintainers summit talk. 

Phillip gave a short talk on how we test 20 backends on Ibis. This talk was not recorded but it was well received. 

- Naty and Phillip gave an Ibis Talk in the Spanish track.  

The talk was well received and we had question at the end of, people were interested and in some cases excited about using Ibis at their workplace.

- Openspace hosted together with DuckDB

Most people in the room (50+) where there to ask questions about duckdb but there were some questions about Ibis. It was good for visibility.

General notes: 
- A maintainer of airflow connected with the team for further discussion
- Multiple ESRI people had interest in knowing more about Geospatial support. 
- The team did a great job making Ibis visible and getting exposure. 

### Other Updates

- Jiting and Deepyaman submitted a proposal for a talk at OSDC West
- Deepyaman submitted a talk proposal for Flink forward

**Comment by ncclementi** [comment]
## Weekly Update
05/30/2024

No update

**Comment by ncclementi** [comment]
## Weekly Update
06/05/2024

No update

**Comment by ncclementi** [comment]
## Weekly Update
06/13/2024

- Chloe delivered a talk at Berlin Buzzwords https://github.com/ibis-project/talks/issues/24
- Deepyman is giving a tutorial on Ibis+Kedro on 06/14 https://github.com/ibis-project/talks/issues/25
- Naty gave an Ibis talk at a local Meetup

**Comment by ncclementi** [comment]
Closing since this was completed!
